version: '3'
services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3002:3000"
    networks:
      - nginx-proxy-manager_enershare_network
    restart: always

networks:
  nginx-proxy-manager_enershare_network:
    external: true
